void statusConnection();
bool connectionWifi();
bool connectSQL();
void setMDNS(char name[]);
void starService();
float getHumidity();
float getTemperature();
void getSensor();
void restServerRouting();
void handleNotFound();
void insertData();